// auth
export const LOGINOUT = 'LOGINOUT'
// village
export const INIT_VILLAGE = 'INIT_VILLAGE'
export const LOAD_VILLAGE = 'LOAD_VILLAGE'
export const STORE_VILLAGE = 'STORE_VILLAGE'
export const STORE_MESSAGES = 'STORE_MESSAGES'
export const STORE_SITUATION = 'STORE_SITUATION'
export const STORE_FILTERING = 'STORE_FILTERING'
export const LOAD_DEBUGVILLAGE = 'LOAD_DEBUGVILLAGE'
// village-settings
export const INIT_VILLAGE_SETTINGS = 'INIT_VILLAGE_SETTINGS'
