export const VILLAGE_STATUS: {
  PROLOGUE: string
  PROGRESS: string
  EPILOGUE: string
  COMPLETE: string
  CANCEL: string
} = {
  PROLOGUE: 'PROLOGUE',
  PROGRESS: 'IN_PROGRESS',
  EPILOGUE: 'EPILOGUE',
  COMPLETE: 'COMPLETED',
  CANCEL: 'CANCEL'
}

export const MESSAGE_TYPE: {
  PUBLIC_SYSTEM: string
  PRIVATE_SYSTEM: string
  PRIVATE_SEER: string
  PRIVATE_PSYCHIC: string
  PRIVATE_WEREWOLF: string
  NORMAL_SAY: string
  MONOLOGUE_SAY: string
  GRAVE_SAY: string
  WEREWOLF_SAY: string
  MASON_SAY: string
  SPECTATE_SAY: string
  CREATOR_SAY: string
  SECRET_SAY: string
  PARTICIPANTS: string
} = {
  PUBLIC_SYSTEM: 'PUBLIC_SYSTEM',
  PRIVATE_SYSTEM: 'PRIVATE_SYSTEM',
  PRIVATE_SEER: 'PRIVATE_SEER',
  PRIVATE_PSYCHIC: 'PRIVATE_PSYCHIC',
  PRIVATE_WEREWOLF: 'PRIVATE_WEREWOLF',
  NORMAL_SAY: 'NORMAL_SAY',
  MONOLOGUE_SAY: 'MONOLOGUE_SAY',
  GRAVE_SAY: 'GRAVE_SAY',
  WEREWOLF_SAY: 'WEREWOLF_SAY',
  MASON_SAY: 'MASON_SAY',
  SPECTATE_SAY: 'SPECTATE_SAY',
  CREATOR_SAY: 'CREATOR_SAY',
  SECRET_SAY: 'SECRET_SAY',
  PARTICIPANTS: 'PARTICIPANTS'
}
