<template>
  <section class="bg-gray-50 py-8">
    <div class="container mx-auto max-w-3xl px-4">
      <!-- 予約村一覧 -->
      <h1 class="mb-4 text-xl font-semibold">予約村</h1>
      <div class="mb-8 text-sm">
        <LoadingSpinner
          v-if="loadingReserved"
          message="予約村を読み込み中..."
        />

        <div
          v-else-if="reservedVillages.length > 0"
          class="overflow-hidden rounded-lg bg-white shadow"
        >
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
              <tr>
                <th
                  class="px-3 py-3 text-left text-sm font-semibold text-gray-900"
                >
                  開始日時
                </th>
                <th
                  class="px-3 py-3 text-left text-sm font-semibold text-gray-900"
                >
                  編成
                </th>
                <th
                  class="px-3 py-3 text-left text-sm font-semibold text-gray-900"
                >
                  沈黙時間
                </th>
                <th
                  class="px-3 py-3 text-left text-sm font-semibold text-gray-900"
                >
                  ダミー役欠け
                </th>
                <th
                  class="px-3 py-3 text-left text-sm font-semibold text-gray-900"
                >
                  初心者村
                </th>
              </tr>
            </thead>
            <tbody class="divide-y divide-gray-200 bg-white">
              <tr v-for="(rv, idx) in reservedVillages" :key="idx">
                <td class="px-3 py-2 text-sm whitespace-nowrap text-gray-900">
                  {{ formatLocalTime(rv.start_time) }}
                </td>
                <td class="px-3 py-2 text-sm text-gray-900">
                  {{ rv.organization }}
                </td>
                <td class="px-3 py-2 text-sm whitespace-nowrap text-gray-900">
                  {{ rv.silent_hours }}時間
                </td>
                <td class="px-3 py-2 text-sm whitespace-nowrap text-gray-900">
                  {{ rv.available_dummy_skill ? 'あり' : 'なし' }}
                </td>
                <td class="px-3 py-2 text-sm whitespace-nowrap text-gray-900">
                  {{ rv.for_beginner ? 'はい' : 'いいえ' }}
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <div v-else class="rounded-lg bg-white p-6 shadow">
          <p class="text-center text-gray-500">予約村がありません</p>
        </div>
      </div>

      <!-- 村作成フォーム -->
      <h2 class="mb-4 text-xl font-semibold">村を作成</h2>
      <div class="rounded-lg bg-white p-6 shadow">
        <div class="space-y-4">
          <FormGroup label="開始日時">
            <input
              v-model="form.startDatetime"
              type="datetime-local"
              class="block w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 focus:border-[var(--ui-primary)] focus:ring-2 focus:ring-[var(--ui-primary)]/20 focus:outline-none"
            />
          </FormGroup>

          <FormGroup label="編成">
            <FormInput
              v-model="form.organization"
              placeholder="編成"
              size="sm"
            />
          </FormGroup>

          <FormGroup label="沈黙時間（時間）">
            <FormNumberInput
              v-model="form.silentHours"
              :min="0"
              :max="24"
              size="sm"
            />
          </FormGroup>

          <FormSwitch
            v-model="form.availableDummySkill"
            label="ダミー役欠けあり"
          />

          <FormSwitch v-model="form.forBeginner" label="初心者村" />

          <div class="pt-4">
            <UiButton
              color="primary"
              :disabled="submitting"
              @click="createVillage"
            >
              村を作成
            </UiButton>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import FormGroup from '~/components/ui/form/FormGroup.vue'
import FormInput from '~/components/ui/form/FormInput.vue'
import FormNumberInput from '~/components/ui/form/FormNumberInput.vue'
import FormSwitch from '~/components/ui/form/FormSwitch.vue'
import type {
  ReservedVillagesView,
  ReservedVillageView,
  AutoGeneratedVillageRegisterBody
} from '~/lib/api/types'

const { apiCall } = useApi()

const reservedVillages = ref<ReservedVillageView[]>([])
const loadingReserved = ref(true)
const submitting = ref(false)

const formatLocalTime = (t: { hour?: number; minute?: number }): string => {
  return `${String(t.hour ?? 0).padStart(2, '0')}:${String(t.minute ?? 0).padStart(2, '0')}`
}

const defaultStartDatetime = (): string => {
  const dt = new Date()
  dt.setDate(dt.getDate() + 4)
  dt.setHours(0, 0, 0, 0)
  const year = dt.getFullYear()
  const month = String(dt.getMonth() + 1).padStart(2, '0')
  const day = String(dt.getDate()).padStart(2, '0')
  return `${year}-${month}-${day}T00:00`
}

const form = reactive({
  organization: '村村村村村村村村村占霊狩狼狼狼狂',
  startDatetime: defaultStartDatetime(),
  silentHours: 0,
  availableDummySkill: false,
  forBeginner: false
})

const formatDateTimeForApi = (datetimeLocalValue: string): string => {
  const dt = new Date(datetimeLocalValue)
  const year = dt.getFullYear()
  const month = String(dt.getMonth() + 1).padStart(2, '0')
  const day = String(dt.getDate()).padStart(2, '0')
  const hours = String(dt.getHours()).padStart(2, '0')
  const minutes = String(dt.getMinutes()).padStart(2, '0')
  const seconds = String(dt.getSeconds()).padStart(2, '0')
  return `${year}-${month}-${day}T${hours}:${minutes}:${seconds}`
}

const loadReservedVillages = async () => {
  loadingReserved.value = true
  try {
    const response = await apiCall<ReservedVillagesView>(
      '/reserved-village/list'
    )
    reservedVillages.value = response.list ?? []
  } catch {
    console.error('予約村の取得に失敗しました')
  } finally {
    loadingReserved.value = false
  }
}

const createVillage = async () => {
  submitting.value = true
  try {
    const body: AutoGeneratedVillageRegisterBody = {
      organization: form.organization,
      start_datetime: formatDateTimeForApi(form.startDatetime),
      silent_hours: form.silentHours,
      available_dummy_skill: form.availableDummySkill,
      for_beginner: form.forBeginner
    }
    await apiCall('/reserved-village', {
      method: 'POST',
      body
    })
    await loadReservedVillages()
  } catch {
    console.error('村の作成に失敗しました')
  } finally {
    submitting.value = false
  }
}

onMounted(() => {
  loadReservedVillages()
})

useSeoMeta({
  title: '村作成 | HOWLING WOLF',
  description: 'HOWLING WOLFで新しい人狼ゲーム村を作成します。'
})
</script>
