export const MESSAGE_TYPE = {
  PUBLIC_SYSTEM: 'PUBLIC_SYSTEM',
  PRIVATE_SYSTEM: 'PRIVATE_SYSTEM',
  PRIVATE_SEER: 'PRIVATE_SEER',
  PRIVATE_PSYCHIC: 'PRIVATE_PSYCHIC',
  PRIVATE_WEREWOLF: 'PRIVATE_WEREWOLF',
  PRIVATE_FANATIC: 'PRIVATE_FANATIC',
  PRIVATE_MASON: 'PRIVATE_MASON',
  PRIVATE_FOX: 'PRIVATE_FOX',
  PRIVATE_SYMPATHIZER: 'PRIVATE_SYMPATHIZER',
  NORMAL_SAY: 'NORMAL_SAY',
  MONOLOGUE_SAY: 'MONOLOGUE_SAY',
  GRAVE_SAY: 'GRAVE_SAY',
  WEREWOLF_SAY: 'WEREWOLF_SAY',
  MASON_SAY: 'MASON_SAY',
  SPECTATE_SAY: 'SPECTATE_SAY',
  CREATOR_SAY: 'CREATOR_SAY',
  SECRET_SAY: 'SECRET_SAY',
  PARTICIPANTS: 'PARTICIPANTS'
} as const

export const MESSAGE_TYPE_GROUP = {
  SYSTEM: 'SYSTEM',
  PRIVATE_SYSTEM: 'PRIVATE_SYSTEM',
  NORMAL_SAY: 'NORMAL_SAY',
  WEREWOLF_SAY: 'WEREWOLF_SAY',
  MASON_SAY: 'MASON_SAY',
  MONOLOGUE_SAY: 'MONOLOGUE_SAY',
  GRAVE_SAY: 'GRAVE_SAY',
  SECRET_SAY: 'SECRET_SAY',
  CREATOR_SAY: 'CREATOR_SAY'
} as const

export type MessageTypeGroup =
  (typeof MESSAGE_TYPE_GROUP)[keyof typeof MESSAGE_TYPE_GROUP]

export const ALL_MESSAGE_TYPE_GROUPS: MessageTypeGroup[] = [
  MESSAGE_TYPE_GROUP.SYSTEM,
  MESSAGE_TYPE_GROUP.PRIVATE_SYSTEM,
  MESSAGE_TYPE_GROUP.NORMAL_SAY,
  MESSAGE_TYPE_GROUP.WEREWOLF_SAY,
  MESSAGE_TYPE_GROUP.MASON_SAY,
  MESSAGE_TYPE_GROUP.MONOLOGUE_SAY,
  MESSAGE_TYPE_GROUP.GRAVE_SAY,
  MESSAGE_TYPE_GROUP.SECRET_SAY,
  MESSAGE_TYPE_GROUP.CREATOR_SAY
]

export const MESSAGE_TYPE_MAP = new Map<
  string,
  'say' | 'system' | 'participants'
>([
  [MESSAGE_TYPE.NORMAL_SAY, 'say'],
  [MESSAGE_TYPE.WEREWOLF_SAY, 'say'],
  [MESSAGE_TYPE.GRAVE_SAY, 'say'],
  [MESSAGE_TYPE.MONOLOGUE_SAY, 'say'],
  [MESSAGE_TYPE.MASON_SAY, 'say'],
  [MESSAGE_TYPE.SPECTATE_SAY, 'say'],
  [MESSAGE_TYPE.SECRET_SAY, 'say'],
  [MESSAGE_TYPE.PUBLIC_SYSTEM, 'system'],
  [MESSAGE_TYPE.PRIVATE_SYSTEM, 'system'],
  [MESSAGE_TYPE.PRIVATE_SEER, 'system'],
  [MESSAGE_TYPE.PRIVATE_PSYCHIC, 'system'],
  [MESSAGE_TYPE.PRIVATE_WEREWOLF, 'system'],
  [MESSAGE_TYPE.PRIVATE_FANATIC, 'system'],
  [MESSAGE_TYPE.PRIVATE_MASON, 'system'],
  [MESSAGE_TYPE.PRIVATE_FOX, 'system'],
  [MESSAGE_TYPE.PRIVATE_SYMPATHIZER, 'system'],
  [MESSAGE_TYPE.CREATOR_SAY, 'system'],
  [MESSAGE_TYPE.PARTICIPANTS, 'participants']
])

/**
 * メッセージタイプ判定関数
 */
export const isSayType = (typeCode: string): boolean => {
  return MESSAGE_TYPE_MAP.get(typeCode) === 'say'
}

export const isSystemType = (typeCode: string): boolean => {
  return MESSAGE_TYPE_MAP.get(typeCode) === 'system'
}

export const isParticipantsType = (typeCode: string): boolean => {
  return MESSAGE_TYPE_MAP.get(typeCode) === 'participants'
}
