/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/village/{villageId}/vote': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['vote']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/village/{villageId}/setting': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['setting']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/village/{villageId}/say': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['say']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/village/{villageId}/say-confirm': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['sayConfirm']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/village/{villageId}/participate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['participateVillage']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/village/{villageId}/participate-confirm': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['participateConfirm']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/village/{villageId}/leave': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['leave']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/village/{villageId}/commit': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['commit']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/village/{villageId}/comingout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['comingout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/village/{villageId}/change-skill': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['changeSkill']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/village/{villageId}/ability': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['ability']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/player/remove-introduce/{playerId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['removeIntroduce']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/player/nickname': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['updateNickname']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/player/introduce/{playerId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['registerIntroduce']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/player/detail': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['updateDetail']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/player/blacklist-player/remove/{playerId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['removeBlacklistPlayer']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/player/blacklist-player/register/{playerId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['registerBlacklistPlayer']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auto-generated-village': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['registerAutoGeneratedVillage']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/village/{villageId}/participate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['participateVillage_1']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/village/{villageId}/no-suddenly-death': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['setNoSuddenlyDeath']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/village/{villageId}/multiple-say': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['multiSay']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/village/{villageId}/kick': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['kick']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/village/{villageId}/dummy-login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['dummyLogin']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/village/{villageId}/change-day': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['changeDay']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/village/{villageId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['village']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/village/{villageId}/situation': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getParticipateSituation']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/village/{villageId}/message/type/{messageType}/number/{messageNumber}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['anchorMessage']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/village/{villageId}/latest': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['findLatest']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/village/{villageId}/day/{day}/time/{noonnight}/message-list': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['message']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/village/list': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['villageList']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/village-record/list': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['villageRecordList']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/village-record/latest-vid': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['latestvillageRecord']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/version': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['version']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/skill/list': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['skills']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/reserved-village/list': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['list']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/recruiting-village-list': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['recruitingVillageList']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/player/{playerId}/record': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['stats']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/my-player': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['myPlayer']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/charachip/{charaChipId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['charachip']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/charachip/{charaChipId}/dummychara': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['dummyChara']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/charachip/list': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['charachipList']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/chara/{charaId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['chara']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/village/{villageId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['village_1']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    VillageVoteBody: {
      /** Format: int32 */
      target_id: number
    }
    VillageSettingBody: {
      hoge?: string
    }
    VillageSayBody: {
      message: string
      message_type: string
      face_type: string
    }
    AbilityType: {
      code: string
      name: string
    }
    AbilityTypes: {
      list: components['schemas']['AbilityType'][]
    }
    Camp: {
      code: string
      name: string
      is_foxs: boolean
    }
    CharaDefaultMessage: {
      join_message?: string
      first_day_message?: string
    }
    CharaFace: {
      type: string
      name: string
      image_url: string
    }
    CharaNameView: {
      name: string
      short_name: string
      full_name: string
    }
    CharaSize: {
      /** Format: int32 */
      width: number
      /** Format: int32 */
      height: number
    }
    CharaView: {
      /** Format: int32 */
      id: number
      chara_name: components['schemas']['CharaNameView']
      /** Format: int32 */
      charachip_id: number
      default_message: components['schemas']['CharaDefaultMessage']
      display: components['schemas']['CharaSize']
      face_list: components['schemas']['CharaFace'][]
    }
    ComingOut: {
      skill: components['schemas']['Skill']
    }
    ComingOuts: {
      list: components['schemas']['ComingOut'][]
    }
    DeadView: {
      code: string
      reason: string
      village_day: components['schemas']['VillageDay']
    }
    MessageContent: {
      type: components['schemas']['MessageType']
      /** Format: int32 */
      num?: number
      /** Format: int32 */
      count?: number
      text: string
      face_code?: string
    }
    MessageTimeView: {
      /** Format: int32 */
      village_day_id: number
      /** Format: int32 */
      day: number
      /** Format: date-time */
      datetime: string
      /** Format: int64 */
      unix_time_milli: number
    }
    MessageType: {
      code: string
      name: string
      is_say_type: boolean
    }
    MessageView: {
      from?: components['schemas']['VillageParticipantView']
      to?: components['schemas']['VillageParticipantView']
      time: components['schemas']['MessageTimeView']
      content: components['schemas']['MessageContent']
    }
    PlayerView: {
      /** Format: int32 */
      id: number
      nickname: string
      twitter_user_name?: string
      other_site_name?: string
      introduction?: string
      introduced: boolean
    }
    Skill: {
      code: string
      name: string
      short_name: string
      win_judge_camp: components['schemas']['Camp']
      ability_list: components['schemas']['AbilityType'][]
      manual_ability_list: components['schemas']['AbilityType'][]
      divine_result_wolf: boolean
      psychic_result_wolf: boolean
      sayable_skill_message_type_list: components['schemas']['MessageType'][]
      viewable_skill_message_type_list: components['schemas']['MessageType'][]
      count_camp?: components['schemas']['Camp']
      description: string
      is_viewable_werewolf_say: boolean
      is_available_werewolf_say: boolean
      abilities: components['schemas']['AbilityTypes']
      is_fox_count: boolean
    }
    SkillRequest: {
      first: components['schemas']['Skill']
      second: components['schemas']['Skill']
    }
    VillageDay: {
      /** Format: int32 */
      id: number
      /** Format: int32 */
      day: number
      noonnight: string
      /** Format: date-time */
      start_datetime: string
      /** Format: date-time */
      day_change_datetime: string
    }
    VillageParticipantView: {
      /** Format: int32 */
      id: number
      chara: components['schemas']['CharaView']
      player?: components['schemas']['PlayerView']
      dead?: components['schemas']['DeadView']
      spectator: boolean
      skill?: components['schemas']['Skill']
      skill_request?: components['schemas']['SkillRequest']
      win?: boolean
      coming_outs: components['schemas']['ComingOuts']
    }
    VillageParticipateBody: {
      /** Format: int32 */
      chara_id: number
      first_request_skill: string
      second_request_skill: string
      join_message: string
      join_password?: string
      spectator?: boolean
    }
    VillageCommitBody: {
      commit: boolean
    }
    VillageComingOutBody: {
      skill_code?: string[]
    }
    VillageChangeSkillBody: {
      first_request_skill: string
      second_request_skill: string
    }
    VillageAbilityBody: {
      /** Format: int32 */
      myself_id?: number
      /** Format: int32 */
      target_id?: number
      ability_type: string
    }
    PlayerUpdateNicknameBody: {
      nickname: string
      twitter_user_name?: string
    }
    PlayerUpdateDetailBody: {
      nickname: string
      other_site_name?: string
      introduction?: string
    }
    AutoGeneratedVillageRegisterBody: {
      organization: string
      /** Format: date-time */
      start_datetime: string
      /** Format: int32 */
      silent_hours?: number
      available_dummy_skill: boolean
      for_beginner: boolean
    }
    VillageRegisterView: {
      /** Format: int32 */
      village_id: number
    }
    AdminParticipateBody: {
      /** Format: int32 */
      participate_count: number
    }
    AdminKickBody: {
      /** Format: int32 */
      target_id?: number
    }
    AdminDummyLoginBody: {
      /** Format: int32 */
      target_id: number
    }
    LocalTime: {
      /** Format: int32 */
      hour?: number
      /** Format: int32 */
      minute?: number
      /** Format: int32 */
      second?: number
      /** Format: int32 */
      nano?: number
    }
    PersonCapacity: {
      /** Format: int32 */
      min: number
      /** Format: int32 */
      max: number
    }
    VillageCharachip: {
      /** Format: int32 */
      dummy_chara_id: number
      /** Format: int32 */
      charachip_id: number
    }
    VillageDayView: {
      /** Format: int32 */
      id: number
      /** Format: int32 */
      day: number
      noonnight: string
      /** Format: date-time */
      start_datetime: string
      /** Format: date-time */
      day_change_datetime: string
      sayable_start_time: components['schemas']['LocalTime']
    }
    VillageDaysView: {
      day_list: components['schemas']['VillageDayView'][]
    }
    VillageMessageRestrict: {
      type: components['schemas']['MessageType']
      /** Format: int32 */
      count: number
      /** Format: int32 */
      length: number
      /** Format: int32 */
      line: number
    }
    VillageMessageRestricts: {
      exist_restricts: boolean
      restrict_list: components['schemas']['VillageMessageRestrict'][]
    }
    VillageOrganizations: {
      organization: {
        [key: string]: string
      }
    }
    VillageParticipantsView: {
      /** Format: int32 */
      count: number
      member_list: components['schemas']['VillageParticipantView'][]
    }
    VillagePasswordView: {
      join_password_required: boolean
    }
    VillageRules: {
      open_vote: boolean
      available_skill_request: boolean
      available_spectate: boolean
      open_skill_in_grave: boolean
      visible_grave_message: boolean
      available_suddenly_death: boolean
      available_commit: boolean
      auto_generated: boolean
      available_dummy_skill: boolean
      for_beginner: boolean
      message_restrict: components['schemas']['VillageMessageRestricts']
    }
    VillageSettingsView: {
      capacity: components['schemas']['PersonCapacity']
      time: components['schemas']['VillageTimeView']
      charachip: components['schemas']['VillageCharachip']
      organizations: components['schemas']['VillageOrganizations']
      rules: components['schemas']['VillageRules']
      password: components['schemas']['VillagePasswordView']
    }
    VillageStatus: {
      code: string
      name: string
      is_canceled: boolean
      is_finished: boolean
      is_prologue: boolean
      is_epilogue: boolean
      is_solved: boolean
      is_progress: boolean
    }
    VillageTimeView: {
      term_type: string
      /** Format: date-time */
      start_datetime: string
      /** Format: int32 */
      day_change_interval_seconds: number
      /** Format: int32 */
      silent_hours?: number
      sayable_start: components['schemas']['LocalTime']
      sayable_end: components['schemas']['LocalTime']
    }
    VillageView: {
      /** Format: int32 */
      id: number
      name: string
      creator_player: components['schemas']['PlayerView']
      status: components['schemas']['VillageStatus']
      win_camp?: components['schemas']['Camp']
      setting: components['schemas']['VillageSettingsView']
      participant: components['schemas']['VillageParticipantsView']
      spectator: components['schemas']['VillageParticipantsView']
      day: components['schemas']['VillageDaysView']
      silent_time: boolean
    }
    Chara: {
      /** Format: int32 */
      id: number
      chara_name: components['schemas']['CharaName']
      /** Format: int32 */
      charachip_id: number
      default_message: components['schemas']['CharaDefaultMessage']
      display: components['schemas']['CharaSize']
      face_list: components['schemas']['CharaFace'][]
    }
    CharaName: {
      name: string
      short_name: string
    }
    SituationAsParticipantView: {
      participate: components['schemas']['VillageParticipateSituationView']
      skill_request: components['schemas']['VillageSkillRequestSituation']
      commit: components['schemas']['VillageCommitSituation']
      coming_out: components['schemas']['VillageComingOutSituation']
      say: components['schemas']['VillageSaySituationView']
      ability: components['schemas']['VillageAbilitySituationsView']
      vote: components['schemas']['VillageVoteSituationView']
      admin: components['schemas']['VillageAdminSituation']
    }
    VillageAbilitySituationView: {
      type: components['schemas']['AbilityType']
      attacker_list: components['schemas']['VillageParticipantView'][]
      attacker?: components['schemas']['VillageParticipantView']
      target_list: components['schemas']['VillageParticipantView'][]
      target?: components['schemas']['VillageParticipantView']
      usable: boolean
      available_no_target: boolean
    }
    VillageAbilitySituationsView: {
      list: components['schemas']['VillageAbilitySituationView'][]
    }
    VillageAdminSituation: {
      admin: boolean
      available_kick: boolean
      participant_list: components['schemas']['VillageParticipantSituation'][]
    }
    VillageComingOutSituation: {
      available_coming_out: boolean
      current_coming_outs: components['schemas']['ComingOuts']
      selectable_skill_list: components['schemas']['Skill'][]
    }
    VillageCommitSituation: {
      available_commit: boolean
      committing: boolean
    }
    VillageParticipantSituation: {
      name: string
      nickname: string
      twitter_user_name?: string
      skill_name?: string
    }
    VillageParticipateSituationView: {
      participating: boolean
      available_participate: boolean
      available_spectate: boolean
      selectable_chara_list: components['schemas']['Chara'][]
      available_leave: boolean
      myself?: components['schemas']['VillageParticipantView']
    }
    VillageSayMessageTypeSituationView: {
      message_type: components['schemas']['MessageType']
      restrict: components['schemas']['VillageSayRestrictSituation']
      target_list: components['schemas']['VillageParticipantView'][]
    }
    VillageSayRestrictSituation: {
      restricted: boolean
      /** Format: int32 */
      max_count?: number
      /** Format: int32 */
      remaining_count?: number
      /** Format: int32 */
      max_length: number
      /** Format: int32 */
      max_line: number
    }
    VillageSaySituationView: {
      available_say: boolean
      selectable_message_type_list: components['schemas']['VillageSayMessageTypeSituationView'][]
      selectable_face_type_list: components['schemas']['CharaFace'][]
      default_message_type?: components['schemas']['MessageType']
    }
    VillageSkillRequestSituation: {
      available_skill_request: boolean
      selectable_skill_list: components['schemas']['Skill'][]
      skill_request?: components['schemas']['SkillRequest']
    }
    VillageVoteSituationView: {
      available_vote: boolean
      target_list: components['schemas']['VillageParticipantView'][]
      target?: components['schemas']['VillageParticipantView']
    }
    VillageAnchorMessageView: {
      message?: components['schemas']['MessageView']
    }
    VillageLatestForm: {
      /** Format: int64 */
      from?: number
    }
    VillageLatestView: {
      /** Format: int64 */
      unix_time_milli: number
      /** Format: int32 */
      village_day_id: number
    }
    VillageMessageForm: {
      message_type_list?: string[]
      participant_id_list?: number[]
      to_participant_id_list?: number[]
      /** Format: int64 */
      from?: number
      keyword?: string
      /** Format: int32 */
      page_size?: number
      /** Format: int32 */
      page_num?: number
      is_disp_latest?: boolean
    }
    MessagesView: {
      list: components['schemas']['MessageView'][]
      /** Format: int32 */
      all_record_count?: number
      /** Format: int32 */
      all_page_count?: number
      exist_pre_page?: boolean
      exist_next_page?: boolean
      /** Format: int32 */
      current_page_num?: number
      is_latest?: boolean
      today_message_count_map: {
        [key: string]: number
      }
    }
    VillageListForm: {
      village_status?: string[]
      is_auto_generate?: boolean
    }
    AccessInfo: {
      ip_address: string
      client_token?: string
    }
    Dead: {
      code: string
      reason: string
      village_day: components['schemas']['VillageDay']
      is_suddenly: boolean
    }
    SimpleVillageView: {
      /** Format: int32 */
      id: number
      name: string
      /** Format: int32 */
      creator_player_id: number
      status: components['schemas']['VillageStatus']
      win_camp?: components['schemas']['Camp']
      setting: components['schemas']['VillageSettingsView']
      participant: components['schemas']['VillageParticipants']
      spectator: components['schemas']['VillageParticipants']
      day: components['schemas']['VillageDays']
    }
    VillageDays: {
      day_list: components['schemas']['VillageDay'][]
    }
    VillageParticipant: {
      /** Format: int32 */
      id: number
      /** Format: int32 */
      chara_id: number
      /** Format: int32 */
      player_id?: number
      dead?: components['schemas']['Dead']
      is_spectator: boolean
      is_gone: boolean
      skill?: components['schemas']['Skill']
      skill_request: components['schemas']['SkillRequest']
      is_win?: boolean
      coming_outs: components['schemas']['ComingOuts']
      access_infos: components['schemas']['AccessInfo'][]
      is_alive: boolean
      is_available_coming_out: boolean
      is_viewable_grave_say: boolean
      is_sayable_grave_say: boolean
      is_viewable_monologue_say: boolean
      is_sayable_monologue_say: boolean
      is_viewable_secret_say: boolean
      is_sayable_secret_say: boolean
      is_viewable_werewolf_say: boolean
      is_sayable_werewolf_say: boolean
      is_viewable_fox_message: boolean
      is_viewable_mason_message: boolean
      is_available_vote: boolean
      is_viewable_spectate_say: boolean
      is_sayable_spectate_say: boolean
      is_dead: boolean
      is_admin: boolean
      is_viewable_attack_message: boolean
      is_viewable_fanatic_message: boolean
      is_viewable_private_system_message: boolean
      is_viewable_psychic_message: boolean
      is_available_skill_request: boolean
    }
    VillageParticipants: {
      /** Format: int32 */
      count: number
      member_list: components['schemas']['VillageParticipant'][]
    }
    VillagesView: {
      list: components['schemas']['SimpleVillageView'][]
    }
    VillageRecordListForm: {
      vid?: number[]
    }
    VillageParticipantRecordView: {
      twitter_user_id: string
      other_site_user_id?: string
      character_name: string
      skill_name?: string
      is_win?: boolean
      is_dead: boolean
      /** Format: int32 */
      dead_day?: number
      dead_reason?: string
    }
    VillageRecordView: {
      /** Format: int32 */
      id: number
      name: string
      status: string
      organization: string
      start_datetime?: string
      prologue_datetime: string
      epilogue_datetime?: string
      /** Format: int32 */
      epilogue_day?: number
      url: string
      win_camp_name?: string
      participant_list: components['schemas']['VillageParticipantRecordView'][]
    }
    VillageRecordsView: {
      list: components['schemas']['VillageRecordView'][]
    }
    LatestVillageRecordView: {
      /** Format: int32 */
      vid: number
    }
    Version: {
      /** Format: int32 */
      client_version: number
    }
    SkillsView: {
      list: components['schemas']['Skill'][]
    }
    ReservedVillageListForm: {
      /** Format: int32 */
      limit?: number
    }
    ReservedVillageView: {
      start_time: components['schemas']['LocalTime']
      organization: string
      /** Format: int32 */
      silent_hours: number
      sayable_start: components['schemas']['LocalTime']
      sayable_end: components['schemas']['LocalTime']
      available_dummy_skill: boolean
      for_beginner: boolean
      can_skill_request: boolean
    }
    ReservedVillagesView: {
      list: components['schemas']['ReservedVillageView'][]
    }
    RecruitingReservedVillageView: {
      name: string
      /** Format: int32 */
      participant_capacity: number
      day_change_time: string
      start_datetime: string
      charachip_name: string
      sayable_time: string
      url: string
      organization: string
    }
    RecruitingVillageView: {
      /** Format: int32 */
      id: number
      name: string
      status: string
      /** Format: int32 */
      participant_count: number
      /** Format: int32 */
      participant_capacity: number
      day_change_time: string
      start_datetime: string
      charachip_name: string
      sayable_time: string
      url: string
      organization: string
    }
    RecruitingVillagesView: {
      village_list: components['schemas']['RecruitingVillageView'][]
      reserved_village_list: components['schemas']['RecruitingReservedVillageView'][]
    }
    CampRecord: {
      camp: components['schemas']['Camp']
      /** Format: int32 */
      participate_count: number
      /** Format: int32 */
      win_count: number
      /** Format: float */
      win_rate: number
    }
    ParticipateVillageView: {
      village: components['schemas']['VillageView']
      participant: components['schemas']['VillageParticipantView']
    }
    PlayerRecordsView: {
      player: components['schemas']['PlayerView']
      whole_record: components['schemas']['Record']
      camp_record_list: components['schemas']['CampRecord'][]
      skill_record_list: components['schemas']['SkillRecord'][]
      participate_village_list: components['schemas']['ParticipateVillageView'][]
    }
    Record: {
      /** Format: int32 */
      participate_count: number
      /** Format: int32 */
      win_count: number
      /** Format: float */
      win_rate: number
    }
    SkillRecord: {
      skill: components['schemas']['Skill']
      /** Format: int32 */
      participate_count: number
      /** Format: int32 */
      win_count: number
      /** Format: float */
      win_rate: number
    }
    MyselfPlayerView: {
      /** Format: int32 */
      id: number
      nickname: string
      twitter_user_name?: string
      available_create_village: boolean
      participate_progress_villages: components['schemas']['VillagesView']
      participate_finished_villages: components['schemas']['VillagesView']
      create_progress_villages: components['schemas']['VillagesView']
      create_finished_villages: components['schemas']['VillagesView']
      blacklist_players: components['schemas']['PlayerView'][]
      introduce_players: components['schemas']['PlayerView'][]
      introduced_players: components['schemas']['PlayerView'][]
    }
    CharachipView: {
      /** Format: int32 */
      id: number
      name: string
      designer: components['schemas']['Designer']
      description_url: string
      chara_list: components['schemas']['Chara'][]
    }
    Designer: {
      /** Format: int32 */
      id: number
      name: string
    }
    CharachipsView: {
      list: components['schemas']['CharachipView'][]
    }
    DebugVillageView: {
      /** Format: int32 */
      id: number
      name: string
      creator_player: components['schemas']['PlayerView']
      status: components['schemas']['VillageStatus']
      setting: components['schemas']['VillageSettingsView']
      participant: components['schemas']['VillageParticipantsView']
      spectator: components['schemas']['VillageParticipantsView']
      day: components['schemas']['VillageDays']
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  vote: {
    parameters: {
      query?: never
      header?: never
      path: {
        villageId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['VillageVoteBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  setting: {
    parameters: {
      query?: never
      header?: never
      path: {
        villageId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['VillageSettingBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  say: {
    parameters: {
      query?: never
      header?: never
      path: {
        villageId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['VillageSayBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  sayConfirm: {
    parameters: {
      query?: never
      header?: never
      path: {
        villageId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['VillageSayBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['MessageView']
        }
      }
    }
  }
  participateVillage: {
    parameters: {
      query?: never
      header?: never
      path: {
        villageId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['VillageParticipateBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  participateConfirm: {
    parameters: {
      query?: never
      header?: never
      path: {
        villageId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['VillageParticipateBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['MessageView']
        }
      }
    }
  }
  leave: {
    parameters: {
      query?: never
      header?: never
      path: {
        villageId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  commit: {
    parameters: {
      query?: never
      header?: never
      path: {
        villageId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['VillageCommitBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  comingout: {
    parameters: {
      query?: never
      header?: never
      path: {
        villageId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['VillageComingOutBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  changeSkill: {
    parameters: {
      query?: never
      header?: never
      path: {
        villageId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['VillageChangeSkillBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  ability: {
    parameters: {
      query?: never
      header?: never
      path: {
        villageId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['VillageAbilityBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  removeIntroduce: {
    parameters: {
      query?: never
      header?: never
      path: {
        playerId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  updateNickname: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PlayerUpdateNicknameBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  registerIntroduce: {
    parameters: {
      query?: never
      header?: never
      path: {
        playerId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  updateDetail: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PlayerUpdateDetailBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  removeBlacklistPlayer: {
    parameters: {
      query?: never
      header?: never
      path: {
        playerId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  registerBlacklistPlayer: {
    parameters: {
      query?: never
      header?: never
      path: {
        playerId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  registerAutoGeneratedVillage: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AutoGeneratedVillageRegisterBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['VillageRegisterView']
        }
      }
    }
  }
  participateVillage_1: {
    parameters: {
      query?: never
      header?: never
      path: {
        villageId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminParticipateBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  setNoSuddenlyDeath: {
    parameters: {
      query?: never
      header?: never
      path: {
        villageId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  multiSay: {
    parameters: {
      query?: never
      header?: never
      path: {
        villageId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  kick: {
    parameters: {
      query?: never
      header?: never
      path: {
        villageId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminKickBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  dummyLogin: {
    parameters: {
      query?: never
      header?: never
      path: {
        villageId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminDummyLoginBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  changeDay: {
    parameters: {
      query?: never
      header?: never
      path: {
        villageId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  village: {
    parameters: {
      query?: never
      header?: never
      path: {
        villageId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['VillageView']
        }
      }
    }
  }
  getParticipateSituation: {
    parameters: {
      query?: never
      header?: never
      path: {
        villageId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['SituationAsParticipantView']
        }
      }
    }
  }
  anchorMessage: {
    parameters: {
      query?: never
      header?: never
      path: {
        villageId: number
        messageType: string
        messageNumber: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['VillageAnchorMessageView']
        }
      }
    }
  }
  findLatest: {
    parameters: {
      query: {
        form: components['schemas']['VillageLatestForm']
      }
      header?: never
      path: {
        villageId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['VillageLatestView']
        }
      }
    }
  }
  message: {
    parameters: {
      query: {
        form: components['schemas']['VillageMessageForm']
      }
      header?: never
      path: {
        villageId: number
        day: number
        noonnight: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['MessagesView']
        }
      }
    }
  }
  villageList: {
    parameters: {
      query: {
        form: components['schemas']['VillageListForm']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['VillagesView']
        }
      }
    }
  }
  villageRecordList: {
    parameters: {
      query: {
        form: components['schemas']['VillageRecordListForm']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['VillageRecordsView']
        }
      }
    }
  }
  latestvillageRecord: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['LatestVillageRecordView']
        }
      }
    }
  }
  version: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['Version']
        }
      }
    }
  }
  skills: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['SkillsView']
        }
      }
    }
  }
  list: {
    parameters: {
      query: {
        form: components['schemas']['ReservedVillageListForm']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ReservedVillagesView']
        }
      }
    }
  }
  recruitingVillageList: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RecruitingVillagesView']
        }
      }
    }
  }
  stats: {
    parameters: {
      query?: never
      header?: never
      path: {
        playerId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PlayerRecordsView']
        }
      }
    }
  }
  myPlayer: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['MyselfPlayerView']
        }
      }
    }
  }
  charachip: {
    parameters: {
      query?: never
      header?: never
      path: {
        charaChipId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['CharachipView']
        }
      }
    }
  }
  dummyChara: {
    parameters: {
      query?: never
      header?: never
      path: {
        charaChipId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['Chara']
        }
      }
    }
  }
  charachipList: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['CharachipsView']
        }
      }
    }
  }
  chara: {
    parameters: {
      query?: never
      header?: never
      path: {
        charaId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['Chara']
        }
      }
    }
  }
  village_1: {
    parameters: {
      query?: never
      header?: never
      path: {
        villageId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['DebugVillageView']
        }
      }
    }
  }
}
